//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KN_KAMPUS_MERDEKA.DAL.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class mRFID_Reader
    {
        public int intReader_id { get; set; }
        public string txtIP_addreess { get; set; }
        public Nullable<int> intLokasiID { get; set; }
        public Nullable<int> intPowerJarak { get; set; }
        public string txtCategory { get; set; }
        public Nullable<int> intPort { get; set; }
        public string txtGUID { get; set; }
        public string txtInsertedBy { get; set; }
        public Nullable<System.DateTime> dtmInsertedBy { get; set; }
        public string txtUpdatedBy { get; set; }
        public Nullable<System.DateTime> dtmUpdatedBy { get; set; }
    }
}
